import Head from 'next/head'
import Image from 'next/image'
import styles from './Home/home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.home}>
        <div className={styles.hero}>
          <img className={styles.float1} src="./hero_float_1.png" alt="" />
          <img className={styles.float2} src="./hero_float_2.png" alt="" />
          <h1 className={styles.title}>
            Learn web3 with <span className={styles.gradText}>Truts</span>
          </h1>
          <h2>The Web3 education platform for developers, by developers</h2>
          <span className={styles.heroBtnSec}>
            <button className={styles.primaryBtn}><img src="./search.png" alt="" />Explore Communities</button>
            <button className={styles.secBtn}><img src="./compass.png" alt="" />Explore Opportunities</button>
          </span>
        </div>
        <div className={styles.content}>
          <div className={styles.section}>
            <h1 className={styles.secTitle}>Chains</h1>
            <div className={styles.resourceCon}>
              <Resource />
              <Resource />
              <Resource />
              <Resource />
              <Resource />
              <Resource />
              <Resource />
              <Resource />
            </div>
          </div>
          <div className={styles.section}>
            <h1 className={styles.secTitle}>Tools</h1>
            <div className={styles.resourceCon}>
              <Resource />
              <Resource />
              <Resource />
              <Resource />
              <Resource />
              <Resource />
              <Resource />
              <Resource />
            </div>
          </div>
          <div className={styles.section}>
            <h1 className={styles.secTitle}>Infra</h1>
            <div className={styles.resourceCon}>
              <Resource />
              <Resource />
              <Resource />
              <Resource />
              <Resource />
              <Resource />
              <Resource />
              <Resource />
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}

const Resource = () => {
  return (
    <div className={styles.resource}>
      <img src="./polygonIcon.png" alt="" />
      <span>
        <h1>Polygon</h1>
        <h3>34 courses</h3>
        <p>Polygon is an Indian blockchain scalability platform. It addresses the challenges faced by Ethereum.</p>
      </span>
    </div>
  )
}